### ISSUE TITLE
Generation of template with an url

### ISSUE THREAD

**Issue by skydjol** [kcl-lang/helm-kcl#58]
### 1. Minimal reproduce step (Required)

Use this command
`template --file ./examples/workload-charts-with-kcl/kcl-run.yaml`

with
```
# kcl-config.yaml
apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: set-annotation
spec:
  # EDIT THE SOURCE!
  # This should be your KCL code which preloads the `ResourceList` to `option("items")
  source: |
    [resource | {if resource.kind == "Deployment": metadata.annotations: {"managed-by" = "helm-kcl-plugin"}} for resource in option("items")]

repositories:
#  - name: workload
#    path: ./workload-charts
   - name: nginx-ingress
     url: https://github.com/nginxinc/kubernetes-ingress/tree/v3.1.0/deployments/helm-chart
```

### 2. What did you expect to see? (Required)

Yaml generated by helm
### 3. What did you see instead (Required)

```
Error: Chart.yaml file is missing
Error: plugin "kcl" exited with error
```
### 4. What is your KCL components version? (Required)
From master

### Comment
I see this condition seems strange
https://github.com/kcl-lang/helm-kcl/blob/main/pkg/app/app.go#L80

```
	if err != nil {
		// Load from url
		chart, err = app.render.LoadChartFromRemoteCharts(chartPath)
		if err != nil {
			return nil, err
		}
	} else {
		// Load from local path
		chart, err = app.render.LoadChartFromLocalDirectory(chartPath)
		if err != nil {
			return nil, err
		}
	}
```

pass always in else condition.
